application: music-we-like-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /auth/.*
  script: auth.application

- url: /.*
  script: main.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  